"""Castor OS AISA v0.1 IPC Client."""

from __future__ import annotations

from .client import (
    MAX_FRAME_BYTES,
    AisaClient,
    AisaClientError,
    AisaConnectionError,
    AisaCorrelationError,
    AisaFrameTooLargeError,
    AisaGatewayError,
    AisaProtocolError,
    AisaTimeoutError,
)
from .operations import (
    ActionBinding,
    AdmitTurn,
    AgentPersistFence,
    AgentRevokeCapability,
    CapabilityGrant,
    CommitTurn,
    ConsumeInteraction,
    EnsureRegion,
    GetProjectionSummary,
    GrantCapability,
    InspectJournal,
    OperatorPersistFence,
    OperatorRevokeCapability,
    PresentAdmissionCertificate,
    QueryOperationDescriptor,
    RecordDispatchAttempt,
    RegisterAction,
    ReportOutcome,
    RequestInteraction,
    ResolveQuarantinedDispute,
    SubmitDecision,
)
from .outcomes import (
    AdmitTurnOutcome,
    CommitTurnOutcome,
    ConsumeInteractionOutcome,
    GrantCapabilityOutcome,
    JournalInspection,
    PersistFenceOutcome,
    PresentAdmissionOutcome,
    ProjectionSummary,
    RecordDispatchOutcome,
    RegionOutcome,
    RegisterActionOutcome,
    ReportOutcomeResult,
    RequestInteractionOutcome,
    ResolveDisputeOutcome,
    RevokeCapabilityOutcome,
    SubmitDecisionOutcome,
)
from .session import (
    AgentRequest,
    AgentSession,
    AisaResponse,
    OperatorRequest,
    OperatorSession,
)

__version__ = "0.7.0a1"

__all__ = [
    "MAX_FRAME_BYTES",
    "AisaClient",
    "AisaClientError",
    "AisaConnectionError",
    "AisaCorrelationError",
    "AisaFrameTooLargeError",
    "AisaGatewayError",
    "AisaProtocolError",
    "AisaTimeoutError",
    "AgentSession",
    "AgentRequest",
    "OperatorRequest",
    "OperatorSession",
    "AisaResponse",
    "ActionBinding",
    "AdmitTurn",
    "AgentPersistFence",
    "AgentRevokeCapability",
    "CapabilityGrant",
    "CommitTurn",
    "ConsumeInteraction",
    "EnsureRegion",
    "GetProjectionSummary",
    "GrantCapability",
    "InspectJournal",
    "OperatorPersistFence",
    "OperatorRevokeCapability",
    "PresentAdmissionCertificate",
    "QueryOperationDescriptor",
    "RecordDispatchAttempt",
    "RegisterAction",
    "ReportOutcome",
    "RequestInteraction",
    "ResolveQuarantinedDispute",
    "SubmitDecision",
    "AdmitTurnOutcome",
    "CommitTurnOutcome",
    "ConsumeInteractionOutcome",
    "GrantCapabilityOutcome",
    "JournalInspection",
    "PersistFenceOutcome",
    "PresentAdmissionOutcome",
    "ProjectionSummary",
    "RecordDispatchOutcome",
    "RegionOutcome",
    "RegisterActionOutcome",
    "ReportOutcomeResult",
    "RequestInteractionOutcome",
    "ResolveDisputeOutcome",
    "RevokeCapabilityOutcome",
    "SubmitDecisionOutcome",
    "__version__",
]
